In [20]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

sms = pd.read_csv("../input/disaster-tweets/tweets.csv")

In [21]:
sms.head()

,id,keyword,location,text,target
0,0,ablaze,NaN,"Communal violence in Bhainsa, Telangana. ""Ston...",1
1,1,ablaze,NaN,Telangana: Section 144 has been imposed in Bha...,1
2,2,ablaze,New York City,Arsonist sets cars ablaze at dealership https:...,1
3,3,ablaze,"Morgantown, WV",Arsonist sets cars ablaze at dealership https:...,1
4,4,ablaze,NaN,"""Lord Jesus, your love brings freedom and pard...",0

In [22]:
sms.text[10]

'Images showing the havoc caused by the #Cameroon military as they torched houses in #Oku.The shameless military is reportedâ€¦'

In [23]:
sms.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11370 entries, 0 to 11369
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        11370 non-null  int64
 1   keyword   11370 non-null  object
 2   location  7952 non-null   object
 3   text      11370 non-null  object
 4   target    11370 non-null  int64
dtypes: int64(2), object(3)
memory usage: 444.3+ KB

In [24]:
sms.dropna(how='any', inplace=True)

In [25]:
sms.head()

,id,keyword,location,text,target
2,2,ablaze,New York City,Arsonist sets cars ablaze at dealership https:...,1
3,3,ablaze,"Morgantown, WV",Arsonist sets cars ablaze at dealership https:...,1
5,5,ablaze,OC,"If this child was Chinese, this tweet would ha...",0
6,6,ablaze,"London, England",Several houses have been set ablaze in Ngemsib...,1
7,7,ablaze,Bharat,Asansol: A BJP office in Salanpur village was ...,1

In [26]:
sms.drop('keyword', axis=1, inplace=True)
sms.drop('location', axis=1, inplace=True)

In [27]:
sms.head()

   id                                               text  target
2   2  Arsonist sets cars ablaze at dealership https:...       1
3   3  Arsonist sets cars ablaze at dealership https:...       1
5   5  If this child was Chinese, this tweet would ha...       0
6   6  Several houses have been set ablaze in Ngemsib...       1
7   7  Asansol: A BJP office in Salanpur village was ...       1

In [28]:
sms.describe()

                 id       target
count   7952.000000  7952.000000
mean    5679.721705     0.192530
std     3260.075795     0.394312
min        2.000000     0.000000
25%     2854.750000     0.000000
50%     5674.500000     0.000000
75%     8507.500000     0.000000
max    11368.000000     1.000000

In [29]:
import string
from nltk.corpus import stopwords

def temp_process(mess):
    STOPWORDS = stopwords.words('english')
    nopunc = [char for char in mess if char not in string.punctuation]
    nopunc = ''.join(nopunc)
    nopunc = ' '.join([word for word in nopunc.split() if word.lower() not in STOPWORDS])
    return nopunc

In [30]:
sms['clean_msg'] = sms.text.apply(temp_process)
sms.head()

,id,text,target,clean_msg
2,2,Arsonist sets cars ablaze at dealership https:...,1,Arsonist sets cars ablaze dealership httpstcog...
3,3,Arsonist sets cars ablaze at dealership https:...,1,Arsonist sets cars ablaze dealership httpstco0...
5,5,"If this child was Chinese, this tweet would ha...",0,child Chinese tweet would gone viral Social me...
6,6,Several houses have been set ablaze in Ngemsib...,1,Several houses set ablaze Ngemsibaa village Ok...
7,7,Asansol: A BJP office in Salanpur village was ...,1,Asansol BJP office Salanpur village set ablaze...

In [31]:
words = sms.clean_msg.apply(lambda x: [word.lower() for word in x.split()])

In [32]:
from collections import Counter
my_words = Counter()

for msg in words:
    my_words.update(msg)
    
print(my_words.most_common(50))

[('amp', 389), ('like', 377), ('people', 349), ('one', 286), ('us', 229), ('fire', 225), ('get', 210), ('im', 192), ('new', 187), ('would', 175), ('know', 172), ('time', 167), ('first', 167), ('emergency', 148), ('tâ€¦', 147), ('need', 147), ('years', 146), ('dont', 144), ('see', 143), ('storm', 143), ('think', 139), ('two', 137), ('itâ€™s', 136), ('2', 135), ('today', 132), ('still', 132), ('many', 127), ('iâ€™m', 127), ('back', 125), ('man', 123), ('iran', 123), ('got', 117), ('body', 117), ('news', 117), ('last', 114), ('1', 113), ('please', 112), ('want', 112), ('fires', 111), ('could', 111), ('also', 111), ('much', 110), ('go', 108), ('â€¦', 108), ('good', 107), ('world', 103), ('even', 102), ('help', 101), ('said', 101), ('killed', 100)]

In [33]:
X = sms.clean_msg
y = sms.target
print(X.shape)
print(y.shape)

(7952,)
(7952,)

In [34]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(5964,)
(5964,)
(1988,)
(1988,)

In [35]:
from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer()
vect.fit(X_train)
X_train_dtm = vect.transform(X_train)

In [36]:
X_test_dtm = vect.transform(X_test)

In [37]:
X_train_dtm

<5964x18659 sparse matrix of type '<class 'numpy.int64'>'
	with 60905 stored elements in Compressed Sparse Row format>

In [40]:
X_test_dtm

<1988x18659 sparse matrix of type '<class 'numpy.int64'>'
	with 16210 stored elements in Compressed Sparse Row format>

In [42]:
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()
nb.fit(X_train_dtm, y_train)

MultinomialNB()

In [43]:
y_pred_class = nb.predict(X_test_dtm)

In [45]:
from sklearn import metrics
metrics.accuracy_score(y_test, y_pred_class)

0.891851106639839

In [47]:
metrics.confusion_matrix(y_test, y_pred_class)

array([[1550,   60],
       [ 155,  223]])